version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: SharedExperinces.WebApi/Dockerfile
    container_name: SharedExperinces.WebApi
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SharedExperincesDB2;User Id=sa;Password=Zerefez7253!;TrustServerCertificate=True
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - Serilog__WriteTo__0__Name=MongoDB 
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://mongodb:27017/LoggingDb
      - Serilog__WriteTo__0__Args__collectionName=log
      - Serilog__WriteTo__0__Args__cappedMaxSizeMb=50
      - Serilog__WriteTo__0__Args__cappedMaxDocuments=10000
      - JWT__Issuer=SecureApi
      - JWT__Audience=SecureApi
      - JWT__Key=JWTAuthenticationSecuredSecretKey12345678
    networks:
      - shared-experiences-network
    volumes:
      - ./logs:/app/logs
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shared-experiences-sqlserver2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zerefez7253!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - shared-experiences-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Zerefez7253!", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
  mongodb:
    image: mongo:latest
    container_name: shared-experiences-mongodb2
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - shared-experiences-network

networks:
  shared-experiences-network:
    driver: bridge

volumes:
  sqlserver-data:
  mongodb-data: 